In [1]:
import pathlib
import os
import pprint

In [2]:
p_file = pathlib.Path('/Users/temp/file.txt')

In [3]:
print(p_file)

\Users\temp\file.txt


In [4]:
p_file.is_file()

False

In [5]:
print(type(p_file))

<class 'pathlib.WindowsPath'>


In [6]:
p_dir = pathlib.Path('/Users/temp/dir')

In [7]:
print(p_dir)

\Users\temp\dir


In [8]:
print(type(p_dir))

<class 'pathlib.WindowsPath'>


In [9]:
p_new_file = pathlib.Path('/Users/temp/new_file.txt')
print(p_new_file.exists())

False


In [ ]:
p_file

In [ ]:
p_file.samefile(p_file_join)

In [11]:
import tensorflow as tf
tf.__version__

'2.8.0'

In [20]:
DIRECTORY_URL = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
FILE_NAMES = ['cowper.txt', 'derby.txt', 'butler.txt']

In [21]:
from tensorflow.keras import utils

In [35]:
path = os.getcwd() + '\\illiad\\'
path

'D:\\workspace\\Pycharm\\tf25\\illiad\\'

In [45]:
DIRECTORY_URL = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
FILE_NAMES = ['cowper.txt', 'derby.txt', 'butler.txt']

for name in FILE_NAMES:
  text_dir = utils.get_file(name, origin=DIRECTORY_URL + name)

parent_dir = pathlib.Path(text_dir).parent
list(parent_dir.iterdir())

[WindowsPath('C:/Users/winston/.keras/datasets/butler.txt'),
 WindowsPath('C:/Users/winston/.keras/datasets/cowper.txt'),
 WindowsPath('C:/Users/winston/.keras/datasets/derby.txt')]

In [47]:
parent_dir/'butler.txt'

WindowsPath('C:/Users/winston/.keras/datasets/butler.txt')

In [49]:
lines_dataset = tf.data.TextLineDataset(str(parent_dir/'butler.txt'))

In [50]:
lines_dataset

<TextLineDatasetV2 element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [51]:
temp = lines_dataset.take(1)

In [52]:
temp

<TakeDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>

In [54]:
for i in temp:
    print(i.numpy())

b'\xef\xbb\xbfSing, O goddess, the anger of Achilles son of Peleus, that brought'


In [59]:
a = 5
temp1 = tf.cast(a, dtype=tf.int64)
temp2 = tf.cast(a+1, dtype=tf.int64)
temp3 = tf.cast(a+2, dtype=tf.int64)

In [60]:
temp3

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [64]:
temp = temp1.concatenate(temp2)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'concatenate'

In [ ]:
AUTOTUNE = tf.data.AUTOTUNE

def configure_dataset(dataset):
    return dataset.cache().prefetch(buffer_size=AUTOTUNE)

In [65]:
def countLetters(word):
    counter = {}
    for letter in word:
        if letter not in counter:
            counter[letter] = 0
        counter[letter] += 1
    return counter

In [68]:
countLetters('c0')

{'c': 1, '0': 1}

In [69]:
from collections import defaultdict

In [70]:
def countLetters(word):
    counter = defaultdict(int)
    for letter in word:
        counter[letter] += 1
    return counter

In [84]:
temp = countLetters('asdf')

In [89]:
temp = defaultdict(list)

In [90]:
temp

defaultdict(list, {})

In [88]:
temp['a'] = 0

TypeError: 'set' object does not support item assignment

In [76]:
vocab_dict = defaultdict(lambda: 0)

In [77]:
vocab_dict

defaultdict(<function __main__.<lambda>()>, {})

In [91]:
from collections import defaultdict

def groupWords(words):
    grouper = defaultdict(list)
    for word in words:
        length = len(word)
        grouper[length].append(word)
    return grouper

In [92]:
groupWords(['asdf', 'asd', 'a', 'b', 'ded'])

defaultdict(list, {4: ['asdf'], 3: ['asd', 'ded'], 1: ['a', 'b']})

In [98]:
def create_model(vocab_size, num_labels):
  model = tf.keras.Sequential([
      layers.Embedding(vocab_size, 64, mask_zero=True),
      layers.Conv1D(64, 5, padding="valid", activation="relu", strides=2),
      layers.GlobalMaxPooling1D(),
      layers.Dense(num_labels)
  ])
  return model

In [ ]:
VOCAB_SIZE = 10000

binary_vectorize_layer = TextVectorization(
    max_tokens=VOCAB_SIZE,
    output_mode='binary')

In [ ]:
MAX_SEQUENCE_LENGTH = 250

int_vectorize_layer = TextVectorization(
    max_tokens=VOCAB_SIZE,
    output_mode='int',
    output_sequence_length=MAX_SEQUENCE_LENGTH)

In [99]:
a, b = [1, 2], [3, 4]

In [100]:
a, b

([1, 2], [3, 4])

In [101]:
for i, j in zip(a, b):
    print(i, j)

1 3
2 4


In [125]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
a = tf.cast(a, dtype=tf.int64)
a

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], dtype=int64)>

In [126]:
temp = tf.expand_dims(a, -1)
temp

<tf.Tensor: shape=(10, 1), dtype=int64, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9],
       [0]], dtype=int64)>