In [1]:
import tensorflow as tf

In [24]:
t1 = tf.random.normal([3, 3, 2])
t2 = tf.random.normal([3, 3, 2])

In [25]:
t1

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.26434615, -0.6805235 ],
        [-0.97812   ,  0.35514578],
        [-0.03363752, -1.1262499 ]],

       [[ 2.0834806 ,  0.6468455 ],
        [ 0.92016   , -0.79960084],
        [ 0.22740962,  0.51522946]],

       [[ 0.5849644 ,  0.7644525 ],
        [ 0.7018904 , -0.8432159 ],
        [-0.41014498, -1.1248293 ]]], dtype=float32)>

In [26]:
t2

<tf.Tensor: shape=(3, 3, 2), dtype=float32, numpy=
array([[[-0.5813757 ,  1.6184088 ],
        [-0.24274835,  0.38060433],
        [ 0.6311598 , -1.2493638 ]],

       [[ 1.5842286 ,  0.5239691 ],
        [-0.56721383,  0.2700439 ],
        [ 0.90118647, -0.62104625]],

       [[ 0.08610526, -0.41170973],
        [-0.3615915 ,  1.1801256 ],
        [ 0.00383392, -1.9785084 ]]], dtype=float32)>

In [31]:
tf.concat((t1, t2), axis=-1)

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[-0.26434615, -0.6805235 , -0.5813757 ,  1.6184088 ],
        [-0.97812   ,  0.35514578, -0.24274835,  0.38060433],
        [-0.03363752, -1.1262499 ,  0.6311598 , -1.2493638 ]],

       [[ 2.0834806 ,  0.6468455 ,  1.5842286 ,  0.5239691 ],
        [ 0.92016   , -0.79960084, -0.56721383,  0.2700439 ],
        [ 0.22740962,  0.51522946,  0.90118647, -0.62104625]],

       [[ 0.5849644 ,  0.7644525 ,  0.08610526, -0.41170973],
        [ 0.7018904 , -0.8432159 , -0.3615915 ,  1.1801256 ],
        [-0.41014498, -1.1248293 ,  0.00383392, -1.9785084 ]]],
      dtype=float32)>