In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.0


# Concat

In [2]:
a, b, c = [0, 0, 0], [1, 1, 1], [2, 2, 2]

In [3]:
a = tf.cast(a, dtype=tf.int64)
b = tf.cast(b, dtype=tf.int64)
c = tf.cast(c, dtype=tf.int64)
a

Metal device set to: Apple M1


2022-08-20 13:24:46.070319: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-08-20 13:24:46.070426: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 0, 0])>

In [4]:
tf.concat([a, b, c], axis=0)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 2, 2, 2])>

In [5]:
tf.concat([a, b, c], axis=-1)

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 2, 2, 2])>

In [6]:
tf.concat([a, b, c], axis=1)

InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

In [7]:
a, b, c = [[0, 0, 0]], [[1, 1, 1]], [[2, 2, 2]]
a = tf.cast(a, dtype=tf.int64)
b = tf.cast(b, dtype=tf.int64)
c = tf.cast(c, dtype=tf.int64)
a

<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[0, 0, 0]])>

In [8]:
tf.concat([a, b, c], axis=0)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])>

In [9]:
tf.concat([a, b, c], axis=1)

<tf.Tensor: shape=(1, 9), dtype=int64, numpy=array([[0, 0, 0, 1, 1, 1, 2, 2, 2]])>

In [10]:
tf.concat([a, b, c], axis=-1)

<tf.Tensor: shape=(1, 9), dtype=int64, numpy=array([[0, 0, 0, 1, 1, 1, 2, 2, 2]])>

In [11]:
a = [[1, 1, 1,], [2, 2, 2,]]
b = [[11, 11, 11], [ 22, 22, 22]]
c = [[111, 111, 111,], [222, 222, 222,]]
a = tf.cast(a, dtype=tf.int64)
b = tf.cast(b, dtype=tf.int64)
c = tf.cast(c, dtype=tf.int64)
a

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [12]:
tf.concat([a, b, c], axis=0)

<tf.Tensor: shape=(6, 3), dtype=int64, numpy=
array([[  1,   1,   1],
       [  2,   2,   2],
       [ 11,  11,  11],
       [ 22,  22,  22],
       [111, 111, 111],
       [222, 222, 222]])>

In [16]:
tf.concat([a, b, c], axis=-1)

<tf.Tensor: shape=(2, 9), dtype=int64, numpy=
array([[  1,   1,   1,  11,  11,  11, 111, 111, 111],
       [  2,   2,   2,  22,  22,  22, 222, 222, 222]])>

In [17]:
tf.concat([a, b, c])

TypeError: Missing required positional argument

# Stack

In [ ]:
a = [[1, 1, 1,], [2, 2, 2,]]
b = [[11, 11, 11], [ 22, 22, 22]]
c = [[111, 111, 111,], [222, 222, 222,]]
a = tf.cast(a, dtype=tf.int64)
b = tf.cast(b, dtype=tf.int64)
c = tf.cast(c, dtype=tf.int64)

In [ ]:
print(a)
print(b)
print(c)

In [ ]:
tf.stack([a, b, c], axis=0)

In [ ]:
tf.stack([a, b, c], axis=1)

In [ ]:
tf.stack([a, b, c], axis=2)

In [ ]:
a, b = [0, 0, 0], [1, 1, 1]

In [ ]:
tf.cast(a, dtype=tf.int64)
tf.cast(b, dtype=tf.int64)

In [ ]:
tf.stack([a, b], axis=0)

In [ ]:
tf.concat([a, b], axis=0)

concat은 형 변환 없고 axis에 맞춰 axis가 더해 지는 형태이지만
stack는 axis하나 추가 되고 axis가 가리는 곳에 axis 추가

# maxarg

In [22]:
a = [[7.7153760e-07, 9.9999821e-01, 1.0628303e-06],
    [2.9710069e-05, 1.9882515e-03, 9.9798208e-01],
    [9.2759687e-01, 4.3422729e-02, 2.8980473e-02]]

In [28]:
a = tf.cast(a, dtype=tf.float32)

axis 0은 최 외곽 [7.7153760e-07, 9.9999821e-01, 1.0628303e-06] 자체를 나타내므로 0 끼리의 max 즉 세로로 

In [27]:
print(tf.math.argmax(a, axis=0))

tf.Tensor([2 0 1], shape=(3,), dtype=int64)


axis 1은 [7.7153760e-07, 9.9999821e-01, 1.0628303e-06] 내부의 각각을 나타내므로 각각 끼리의 max 가로로