In [3]:
import tensorflow as tf
import numpy as np

In [4]:
print(tf.__version__)

2.8.0


In [5]:
adapt_data = np.array([1., 2., 3., 4., 5.], dtype='float32')

In [6]:
input_data = np.array([1., 2., 3.], dtype='float32')

In [7]:
layer = tf.keras.layers.Normalization(axis=None)

In [8]:
layer.adapt(adapt_data)

Metal device set to: Apple M1


2022-08-04 08:55:16.819448: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-08-04 08:55:16.819548: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-08-04 08:55:16.845694: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-08-04 08:55:16.896420: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-08-04 08:55:16.910285: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [9]:
layer(input_data)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-1.4142137, -0.7071068,  0.       ], dtype=float32)>

In [38]:
t1 = [[0, 0, 0], [1, 1, 1]]
t2 = [[2, 2, 2], [3, 3, 3]]

In [39]:
t1 = tf.cast(t1, dtype=tf.float32)
t1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [1., 1., 1.]], dtype=float32)>

In [40]:
t2 = tf.cast(t2, dtype=tf.float32) 
t2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 2., 2.],
       [3., 3., 3.]], dtype=float32)>

In [41]:
values=[]
values.append(t1)
values.append(t2)
values

[<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[2., 2., 2.],
        [3., 3., 3.]], dtype=float32)>]

In [42]:
fun = tf.stack(values, axis=-1)
fun

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[0., 2.],
        [0., 2.],
        [0., 2.]],

       [[1., 3.],
        [1., 3.],
        [1., 3.]]], dtype=float32)>